# Generated by Django 5.2 on 2025-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('message', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='پیام')),
            ],
        ),
    ]
